
const countryTranslations = {
    "Finland": "Suomi",
    "Sweden": "Ruotsi",
    "Norway": "Norja",
    "Denmark": "Tanska",
    "Germany": "Saksa",
    "France": "Ranska",
    "Italy": "Italia",
    "Spain": "Espanja",
    "Japan": "Japani",
    "United States": "Yhdysvallat",
    "Canada": "Kanada",
    "Afghanistan": "Afganistan",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua ja Barbuda",
    "Argentina": "Argentiina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Itävalta",
    "Azerbaijan": "Azerbaidžan",
    "Bahamas": "Bahama",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Valko-Venäjä",
    "Belgium": "Belgia",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia ja Hertsegovina",
    "Botswana": "Botswana",
    "Brazil": "Brasilia",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Kap Verde",
    "Cambodia": "Kambodža",
    "Cameroon": "Kamerun",
    "Central African Republic": "Keski-Afrikan tasavalta",
    "Chad": "Tšad",
    "Chile": "Chile",
    "China": "Kiina",
    "Colombia": "Kolumbia",
    "Comoros": "Komorit",
    "Congo (Congo-Brazzaville)": "Kongon tasavalta",
    "Congo (Congo-Kinshasa)": "Kongon demokraattinen tasavalta",
    "Costa Rica": "Costa Rica",
    "Croatia": "Kroatia",
    "Cuba": "Kuuba",
    "Cyprus": "Kypros",
    "Czech Republic (Czechia)": "Tšekki",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominikaaninen tasavalta",
    "Ecuador": "Ecuador",
    "Egypt": "Egypti",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Päiväntasaajan Guinea",
    "Eritrea": "Eritrea",
    "Estonia": "Viro",
    "Eswatini": "Eswatini (Swazimaa)",
    "Ethiopia": "Etiopia",
    "Fiji": "Fidži",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Greece": "Kreikka",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Unkari",
    "Iceland": "Islanti",
    "India": "Intia",
    "Indonesia": "Indonesia",
    "Iran": "Iran",
    "Iraq": "Irak",
    "Ireland": "Irlanti",
    "Israel": "Israel",
    "Jamaica": "Jamaika",
    "Jordan": "Jordania",
    "Kazakhstan": "Kazakstan",
    "Kenya": "Kenia",
    "Kiribati": "Kiribati",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kirgisia",
    "Laos": "Laos",
    "Latvia": "Latvia",
    "Lebanon": "Libanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Liettua",
    "Luxembourg": "Luxemburg",
    "Madagascar": "Madagaskar",
    "Malawi": "Malawi",
    "Malaysia": "Malesia",
    "Maldives": "Malediivit",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Marshallinsaaret",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Meksiko",
    "Micronesia": "Mikronesia",
    "Moldova": "Moldova",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Marokko",
    "Mozambique": "Mosambik",
    "Myanmar (Burma)": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Alankomaat",
    "New Zealand": "Uusi-Seelanti",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Korea": "Pohjois-Korea",
    "North Macedonia": "Pohjois-Makedonia",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Panama": "Panama",
    "Papua New Guinea": "Papua-Uusi-Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Filippiinit",
    "Poland": "Puola",
    "Portugal": "Portugali",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Venäjä",
    "Rwanda": "Ruanda",
    "Saint Kitts and Nevis": "Saint Kitts ja Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent and the Grenadines": "Saint Vincent ja Grenadiinit",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "São Tomé and Príncipe": "São Tomé ja Príncipe",
    "Saudi Arabia": "Saudi-Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychellit",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "Solomon Islands": "Salomonsaaret",
    "Somalia": "Somalia",
    "South Africa": "Etelä-Afrikka",
    "South Korea": "Etelä-Korea",
    "South Sudan": "Etelä-Sudan",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Syria": "Syyria",
    "Tajikistan": "Tadžikistan",
    "Tanzania": "Tansania",
    "Thailand": "Thaimaa",
    "Timor-Leste": "Itä-Timor",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad ja Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Turkki",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ukraina",
    "United Arab Emirates": "Arabiemiirikunnat",
    "United Kingdom": "Yhdistynyt kuningaskunta",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Vatikaani",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Yemen": "Jemen",
    "Zambia": "Sambia",
    "Zimbabwe": "Zimbabwe"
};

export default countryTranslations;
